/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;
import classes.Cliente;
import classes.Endereço;
import javax.swing.JOptionPane;
import persistencia.ClienteDAO;



/**
 *
 * @author curso
 */
public class Form_Cliente extends javax.swing.JFrame {

    /**
     * Creates new form Form_Usuario
     */
    Cliente cliente = null;
    Endereço endereco = null;
    public Form_Cliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jTextField1 = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campo_nome = new javax.swing.JTextField();
        campo_codigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        viuvo = new javax.swing.JRadioButton();
        solteiro = new javax.swing.JRadioButton();
        casado = new javax.swing.JRadioButton();
        divorciado = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        campo_telefone = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        campo_email = new javax.swing.JTextField();
        botao_buscar = new javax.swing.JButton();
        campo_cpf = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        campo_logradouro = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        campo_complemento = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        campo_cidade = new javax.swing.JTextField();
        campo_estado = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        campo_cep = new javax.swing.JFormattedTextField();
        Cadastrar = new javax.swing.JButton();
        atualizar = new javax.swing.JButton();
        limpar = new javax.swing.JButton();
        sair = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jTextField1.setText("jTextField1");

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Preenchimento dos Dados do Cliente");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados Pessoais", 0, 0, new java.awt.Font("Arial", 1, 14), new java.awt.Color(51, 51, 255))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(0, 51, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel1.setText("Código");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setText("Nome Completo");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));
        jPanel1.add(campo_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 460, 30));
        jPanel1.add(campo_codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 120, 30));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel3.setText("CPF");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel4.setText("Estado Civil");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        buttonGroup1.add(viuvo);
        viuvo.setText("Viúvo");
        jPanel3.add(viuvo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, -1, -1));

        buttonGroup1.add(solteiro);
        solteiro.setText("Solteiro");
        jPanel3.add(solteiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        buttonGroup1.add(casado);
        casado.setText("Casado");
        jPanel3.add(casado, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        buttonGroup1.add(divorciado);
        divorciado.setText("Divorciado");
        jPanel3.add(divorciado, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 430, 70));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel5.setText("Telefone de Contato");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        try {
            campo_telefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(campo_telefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 150, 30));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel6.setText("E-mail");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, -1, -1));
        jPanel1.add(campo_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 230, 30));

        botao_buscar.setText("Buscar (Pelo CPF)");
        botao_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_buscarActionPerformed(evt);
            }
        });
        jPanel1.add(botao_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, 130, 30));

        try {
            campo_cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campo_cpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_cpfActionPerformed(evt);
            }
        });
        jPanel1.add(campo_cpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 210, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 240));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Endereço Completo", 0, 0, new java.awt.Font("Arial", 1, 14), new java.awt.Color(51, 51, 255))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel7.setText("Logradouro");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));
        jPanel2.add(campo_logradouro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 220, 30));

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel8.setText("Complemento");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));
        jPanel2.add(campo_complemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 260, 30));

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel9.setText("Cidade");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));
        jPanel2.add(campo_cidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 210, 30));

        campo_estado.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        campo_estado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Acre (AC)", "Alagoas (AL)", "Amapá (AP)", "Amazonas (AM)", "Bahia (BA)", "Ceará (CE)", "Distrito Federal (DF)", "Espírito Santo (ES)", "Goiás (GO)", "Maranhão (MA)", "Mato Grosso (MT)", "Mato Grosso do Sul (MS)", "Minas Gerais (MG)", "Pará (PA)", "Paraíba (PB)", "Paraná (PR)", "Pernambuco (PE)", "Piauí (PI)", "Rio de Janeiro (RJ)", "Rio Grande do Norte (RN)", "Rio Grande do Sul (RS)", "Rondônia (RO)", "Roraima (RR)", "Santa Catarina (SC)", "São Paulo (SP)", "Sergipe (SE)", "Tocantins (TO)" }));
        campo_estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_estadoActionPerformed(evt);
            }
        });
        jPanel2.add(campo_estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 190, 30));

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel10.setText("Estado");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, -1, -1));

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel11.setText("CEP");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, -1, -1));

        try {
            campo_cep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(campo_cep, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 120, 150, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 670, 180));

        Cadastrar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        Cadastrar.setText("Cadastrar");
        Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(Cadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 160, 40));

        atualizar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        atualizar.setText("Atualizar");
        atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarActionPerformed(evt);
            }
        });
        getContentPane().add(atualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, 150, 40));

        limpar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        limpar.setText("Limpar");
        limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparActionPerformed(evt);
            }
        });
        getContentPane().add(limpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 450, 130, 40));

        sair.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        sair.setForeground(new java.awt.Color(153, 0, 0));
        sair.setText("Sair");
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });
        getContentPane().add(sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(563, 463, 100, 40));

        setSize(new java.awt.Dimension(678, 549));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        dispose();
    }//GEN-LAST:event_sairActionPerformed

    private void CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarActionPerformed
        /*Pegar os valores do texto, quando clicar em cadastrar
          1ª forma: (criar uma variavel para cada campo que quiser pegar
       -> int cod = Integer.parseInt(campo_codigo.getText()); */
        
        //2ª forma \/
       Cliente cliente = new Cliente();
       cliente.setCodigo(campo_codigo.getText()); //interger para converter o string para int
       cliente.setNome(campo_nome.getText());
       cliente.setTelefone(campo_telefone.getText());
       cliente.setEmail(campo_email.getText());
       cliente.setCPF(campo_cpf.getText());
       
       Endereço end = new Endereço();
       end.setCidade(campo_cidade.getText());
       end.setLogradouro(campo_logradouro.getText());
       end.setComplemento(campo_complemento.getText());
       end.setCep(campo_cep.getText());
       //pegar texto comboBox \/
       end.setEstado((String)campo_estado.getSelectedItem()); 
       cliente.setEndereco(end);

       //pegar informação do radio button
       String estcivil = "";
                if(solteiro.isSelected()) 
                    estcivil = solteiro.getText();
                else if(casado.isSelected())
                        estcivil = casado.getText();
                
                else if(divorciado.isSelected())
                        estcivil = divorciado.getText();
                
                else if(viuvo.isSelected())
                        estcivil = viuvo.getText();
                cliente.setEstado_civil(estcivil);
                
                cliente.setEndereco(end);
                
                ClienteDAO.addCliente(cliente);
                
                JOptionPane.showMessageDialog(null, "Casdrado com sucesso", "Atenção!", JOptionPane.OK_CANCEL_OPTION );
                
        campo_cep.setText(null);
        campo_cidade.setText(null);
        campo_codigo.setText(null);
        campo_complemento.setText(null);
        campo_cpf.setText(null);
        campo_email.setText(null);
        campo_estado.setSelectedIndex(-1);
        campo_logradouro.setText(null);
        campo_nome.setText(null);
        campo_telefone.setText(null);
        buttonGroup1.clearSelection();
                
                
    
    }//GEN-LAST:event_CadastrarActionPerformed

    private void campo_cpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_cpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_cpfActionPerformed

    private void limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparActionPerformed
        campo_cep.setText(null);
        campo_cidade.setText(null);
        campo_codigo.setText(null);
        campo_complemento.setText(null);
        campo_cpf.setText(null);
        campo_email.setText(null);
        campo_estado.setSelectedIndex(-1);
        campo_logradouro.setText(null);
        campo_nome.setText(null);
        campo_telefone.setText(null);
        buttonGroup1.clearSelection();
        
        
    }//GEN-LAST:event_limparActionPerformed

    private void campo_estadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_estadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_estadoActionPerformed

    private void botao_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_buscarActionPerformed
        String cpf = campo_cpf.getText();
        
        cliente = ClienteDAO.getCliente(cpf);
        //ve se o CPF está correto
        if (cliente != null)
        {
            campo_codigo.setText(cliente.getCodigo());
            campo_nome.setText(cliente.getNome());
            campo_telefone.setText((cliente.getTelefone()));
            campo_email.setText(cliente.getEmail());
            campo_cidade.setText(endereco.getCidade());
            atualizar.setEnabled(true);
            
            
        }
        else
            JOptionPane.showMessageDialog(null,"Cliente não encontrado", "Atenção", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_botao_buscarActionPerformed

    private void atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_atualizarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cadastrar;
    private javax.swing.JButton atualizar;
    private javax.swing.JButton botao_buscar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JFormattedTextField campo_cep;
    private javax.swing.JTextField campo_cidade;
    private javax.swing.JTextField campo_codigo;
    private javax.swing.JTextField campo_complemento;
    private javax.swing.JFormattedTextField campo_cpf;
    private javax.swing.JTextField campo_email;
    private javax.swing.JComboBox campo_estado;
    private javax.swing.JTextField campo_logradouro;
    private javax.swing.JTextField campo_nome;
    private javax.swing.JFormattedTextField campo_telefone;
    private javax.swing.JRadioButton casado;
    private javax.swing.JRadioButton divorciado;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton limpar;
    private javax.swing.JButton sair;
    private javax.swing.JRadioButton solteiro;
    private javax.swing.JRadioButton viuvo;
    // End of variables declaration//GEN-END:variables
public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Cliente().setVisible(true);
            }
        });
    }
}



