/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

/**
 *
 * @author curso
 */
public class Menu_Consultas extends javax.swing.JFrame {

    /**
     * Creates new form Form_principal
     */
    public Menu_Consultas() {
        initComponents();
        this.setExtendedState(this.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar2 = new javax.swing.JMenuBar();
        Menu_Cadastro = new javax.swing.JMenu();
        menuItemClientes = new javax.swing.JMenuItem();
        menuItemProduto = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuItemSair = new javax.swing.JMenuItem();
        menuItemConsultas = new javax.swing.JMenu();
        menuItemCliente = new javax.swing.JMenuItem();
        menuItemProdutos = new javax.swing.JMenuItem();
        menuItemCompra = new javax.swing.JMenu();
        menuItemDiaria = new javax.swing.JMenuItem();
        menuItemMensal = new javax.swing.JMenuItem();
        menuItemAnual = new javax.swing.JMenuItem();
        menu_Compras = new javax.swing.JMenu();
        menuItemNovaCompra = new javax.swing.JMenuItem();
        menuItemNF = new javax.swing.JMenuItem();
        Menu_Suporte = new javax.swing.JMenu();
        menuItemAjuda = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuItemSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 290));

        Menu_Cadastro.setText("Cadastros");

        menuItemClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        menuItemClientes.setText("Clientes");
        menuItemClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemClientesActionPerformed(evt);
            }
        });
        Menu_Cadastro.add(menuItemClientes);

        menuItemProduto.setText("Produtos");
        Menu_Cadastro.add(menuItemProduto);
        Menu_Cadastro.add(jSeparator1);

        menuItemSair.setText("Sair");
        menuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSairActionPerformed(evt);
            }
        });
        Menu_Cadastro.add(menuItemSair);

        jMenuBar2.add(Menu_Cadastro);

        menuItemConsultas.setText("Consultas");

        menuItemCliente.setText("Clientes");
        menuItemCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemClienteActionPerformed(evt);
            }
        });
        menuItemConsultas.add(menuItemCliente);

        menuItemProdutos.setText("Produtos");
        menuItemConsultas.add(menuItemProdutos);

        menuItemCompra.setText("Compras");

        menuItemDiaria.setText("Diaria");
        menuItemCompra.add(menuItemDiaria);

        menuItemMensal.setText("Mensal");
        menuItemCompra.add(menuItemMensal);

        menuItemAnual.setText("Anual");
        menuItemCompra.add(menuItemAnual);

        menuItemConsultas.add(menuItemCompra);

        jMenuBar2.add(menuItemConsultas);

        menu_Compras.setText("Compras");

        menuItemNovaCompra.setText("Nova Compra");
        menu_Compras.add(menuItemNovaCompra);

        menuItemNF.setText("Emitir Nota Fiscal");
        menu_Compras.add(menuItemNF);

        jMenuBar2.add(menu_Compras);

        Menu_Suporte.setText("Suporte");

        menuItemAjuda.setText("Ajuda");
        Menu_Suporte.add(menuItemAjuda);
        Menu_Suporte.add(jSeparator2);

        menuItemSobre.setText("Sobre");
        menuItemSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSobreActionPerformed(evt);
            }
        });
        Menu_Suporte.add(menuItemSobre);

        jMenuBar2.add(Menu_Suporte);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemClienteActionPerformed
        form_consultaCliente fcc = new form_consultaCliente();
        fcc.setVisible(true);
    }//GEN-LAST:event_menuItemClienteActionPerformed

    private void menuItemClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemClientesActionPerformed
        Form_Cliente fc = new Form_Cliente();
       fc.setVisible(true);
    }//GEN-LAST:event_menuItemClientesActionPerformed

    private void menuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuItemSairActionPerformed

    private void menuItemSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSobreActionPerformed
        Form_Sobre fs = new Form_Sobre();
        fs.setVisible(true);
    }//GEN-LAST:event_menuItemSobreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Consultas().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Menu_Cadastro;
    private javax.swing.JMenu Menu_Suporte;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuItem menuItemAjuda;
    private javax.swing.JMenuItem menuItemAnual;
    private javax.swing.JMenuItem menuItemCliente;
    private javax.swing.JMenuItem menuItemClientes;
    private javax.swing.JMenu menuItemCompra;
    private javax.swing.JMenu menuItemConsultas;
    private javax.swing.JMenuItem menuItemDiaria;
    private javax.swing.JMenuItem menuItemMensal;
    private javax.swing.JMenuItem menuItemNF;
    private javax.swing.JMenuItem menuItemNovaCompra;
    private javax.swing.JMenuItem menuItemProduto;
    private javax.swing.JMenuItem menuItemProdutos;
    private javax.swing.JMenuItem menuItemSair;
    private javax.swing.JMenuItem menuItemSobre;
    private javax.swing.JMenu menu_Compras;
    // End of variables declaration//GEN-END:variables
}
